Upgraded golang/x/net to 0.24 to fix vuln
openshift/configuration-anomaly-detection pull request #265
Opened 2024-04-19 20:12 UTC by npecka

Per https://issues.redhat.com/browse/OSD-22354

2024-04-19 20:41 UTC, typeid requested changes

2024-04-19 20:41 UTC, typeid commented on go.mod
> +toolchain go1.22.2
We can't bump to 1.22 yet
/hold

2024-04-19 21:28 UTC, npecka commented
@typeid Latest commit should fix the issue

2024-04-22 06:38 UTC, typeid requested changes

2024-04-22 06:38 UTC, typeid commented on go.mod
> +go 1.21
Bumping this requires bumping other things in this repo. Can this PR just bump golang/x/net to 0.24, so that we can bump the rest at another time?

2024-04-22 06:38 UTC, typeid commented
/unhold

2024-04-25 17:23 UTC, typeid approved these changes
/lgtm
/approve

2024-04-25 18:11 UTC, merged